/** @format */

import * as types from "./types";

// live Url.....
export const BASE_URL = "http://172.105.47.18/api/v1/";
//testing url amar pc
// export const BASE_URL = "http://192.168.1.36:3060/api/v1/";
export const BASE_URL_RESTRO = BASE_URL + "restro/";
export const BASE_URL_GROCERY = BASE_URL + "grocery/";
export const BASE_URL_DRIVER = BASE_URL + "driver/";

export const BASE_URL_GROCERY_DRIVER = BASE_URL + "groceryDriver/";
export const BASE_URL_PRODUCT = BASE_URL + "product/";
export const BASE_URL_PRODUCT_GROCERY = BASE_URL + "groceryProduct/";
export const BASE_URL_ORDER = BASE_URL + "order/";
export const BASE_URL_ORDER_GROCERY = BASE_URL + "groceryOrder/";

// export const BASE_URL_DISCOUNT_LIST =
// 	BASE_URL_ORDER_GROCERY + "discount_report";
// *********** //

///////////////*****************////////////////////

export const API_URL_MANAGMENT_POLICY =
	BASE_URL + types.API_URL_MANAGMENT_POLICY;
export const API_URL_SETTING_MANAGMENT =
	BASE_URL + types.API_URL_SETTING_MANAGMENT;
export const API_URL_RESTAURANT_DRIVER_REPORT =
	BASE_URL_ORDER + types.API_URL_ORDER_BY_DRIVER_REPORT;
export const API_URL_GROCERY_DRIVER_REPORT =
	BASE_URL_ORDER_GROCERY + types.API_URL_ORDER_BY_DRIVER_REPORT;
// id base, type same restaurant and grocery new
export const API_URL_RESTAURANT_DRIVER_REPORT_ID =
	BASE_URL_ORDER + types.API_URL_RESTAURANT_DRIVER_REPORT_ID;
export const API_URL_GROCERY_DRIVER_REPORT_ID =
	BASE_URL_ORDER_GROCERY + types.API_URL_RESTAURANT_DRIVER_REPORT;
//*************** */
export const API_URL_DISCOUNT_LIST =
	BASE_URL_ORDER_GROCERY + types.API_URL_DISCOUNT_LIST;

export const API_URL_ITEM_WISE_SAle_Report =
	BASE_URL_ORDER + types.API_URL_ITEM_WISE_SAle_Report;

export const API_URL_ITEM_WISE_GROCERY_SAle_Report =
	BASE_URL_ORDER_GROCERY + types.API_URL_ITEM_WISE_SAle_Report;

export const BASE_URL_OFFICE = BASE_URL + "office/";
export const BASE_URL_OFFICE_GROCERY = BASE_URL + "groceryOffice/";

// groceryOrder/orderList_cancelled
// export const API_GROCERY_CANCEL = BASE_URL + types.API_GROCERY_CANCEL;
export const API_GROCERY_CANCEL = BASE_URL + "groceryOrder/orderList_cancelled";

export const BASE_URL_GEOCODE =
	"https://maps.googleapis.com/maps/api/geocode/json?";
export const API_GET_ADDRESS_FROM_GOOGLE =
	BASE_URL_GEOCODE + types.API_GET_ADDRESS_FROM_GOOGLE;

export const API_SEND_OTP = BASE_URL + types.API_SEND_OTP;

export const API_ADD_CATEGORY = BASE_URL + types.API_ADD_CATEGORY;
export const API_EDIT_CATEGORY = BASE_URL + types.API_EDIT_CATEGORY;
export const API_LIST_CATEGORY = BASE_URL + types.API_LIST_CATEGORY;
export const API_LIST_GROCERY_CATEGORY =
	BASE_URL + types.API_LIST_GROCERY_CATEGORY;
export const API_DELETE_CATEGORIES = BASE_URL + types.API_DELETE_CATEGORIES;
export const API_DELETE_CATEGORIES_GROCERY =
	BASE_URL + types.API_DELETE_CATEGORIES_GROCERY;
export const API_CHANGE_STATUS_CATEGORY =
	BASE_URL + types.API_CHANGE_STATUS_CATEGORY;

export const API_ADD_CATEGORY_PRODUCT =
	BASE_URL_PRODUCT + types.API_ADD_CATEGORY;
export const API_EDIT_CATEGORY_PRODUCT =
	BASE_URL_PRODUCT + types.API_EDIT_CATEGORY;
export const API_LIST_CATEGORY_PRODUCT =
	BASE_URL_PRODUCT + types.API_LIST_CATEGORY;
export const API_DELETE_CATEGORIES_PRODUCT =
	BASE_URL_PRODUCT + types.API_DELETE_CATEGORIES;
export const API_CHANGE_STATUS_CATEGORY_PRODUCT =
	BASE_URL_PRODUCT + types.API_CHANGE_STATUS_CATEGORY;

export const API_ADD_CATEGORY_PRODUCT_GROCERY =
	BASE_URL + types.API_ADD_CATEGORY_GROCERY;
export const API_EDIT_CATEGORY_PRODUCT_GROCERY =
	BASE_URL + types.API_EDIT_CATEGORY_GROCERY;
export const API_LIST_CATEGORY_PRODUCT_GROCERY =
	BASE_URL + types.API_LIST_GROCERY_CATEGORY;
export const API_DELETE_CATEGORIES_PRODUCT_GROCERY =
	BASE_URL + types.API_DELETE_CATEGORIES_GROCERY;
export const API_CHANGE_STATUS_CATEGORY_PRODUCT_GROCERY =
	BASE_URL + types.API_CHANGE_STATUS_CATEGORY_GROCERY;

export const API_VERIFY_OTP = BASE_URL + types.API_VERIFY_OTP;
export const API_HOMEPAGE = BASE_URL + types.API_HOMEPAGE;
export const API_PROFILE_RESTRO = BASE_URL + types.API_PROFILE_RESTRO;

export const API_LOGOUT = BASE_URL + types.API_LOGOUT;
export const API_LOGIN = BASE_URL + types.API_LOGIN;
export const API_LOGIN_RESTRO = BASE_URL_RESTRO + types.API_LOGIN_RESTRO;
export const API_LOGIN_GROCERY = BASE_URL_GROCERY + types.API_LOGIN_GROCERY;
export const API_ADDRESTRO = BASE_URL_RESTRO + types.API_ADDRESTRO;
export const API_ADDGROCERY = BASE_URL_GROCERY + types.API_ADDGROCERY;
export const API_RESTRO_LIST = BASE_URL_RESTRO + types.API_RESTRO_LIST;
export const API_RALWAY_PARCEL_LISTING =
	BASE_URL + types.API_RALWAY_PARCEL_LISTING;
export const API_PARTY_BOOKING_LISTING =
	BASE_URL + types.API_PARTY_BOOKING_LISTING;
export const API_RALWAY_PARCEL_DELETE =
	BASE_URL + types.API_RALWAY_PARCEL_DELETE;
export const API_PARTY_BOOKING_DELETE =
	BASE_URL + types.API_PARTY_BOOKING_DELETE;
export const API_GROCERY_LIST = BASE_URL_GROCERY + types.API_GROCERY_LIST;
export const API_RESTAURENT_DETAILS =
	BASE_URL_RESTRO + types.API_RESTAURENT_DETAILS;
export const API_GROCERY_DETAILS = BASE_URL_GROCERY + types.API_GROCERY_DETAILS;
export const API_STORE_TYPE = BASE_URL + types.API_STORE_TYPE;

export const API_DELETE_RESTRO = BASE_URL_RESTRO + types.API_DELETE_RESTRO;
export const API_REQ_RESTRO_COUNT =
	BASE_URL_RESTRO + types.API_REQ_RESTRO_COUNT;
export const API_REQ_GROCERY_COUNT =
	BASE_URL_GROCERY + types.API_REQ_GROCERY_COUNT;
export const API_FOR_RECENTDATA_RESTRO_DASHBOARD =
	BASE_URL_RESTRO + types.API_FOR_RECENTDATA_RESTRO_DASHBOARD;
export const API_FOR_RECENTDATA_GROCERY_DASHBOARD =
	BASE_URL_GROCERY + types.API_FOR_RECENTDATA_GEOCERY_DASHBOARD;

export const API_DELETE_PRODUCT_GROCERY =
	BASE_URL_PRODUCT_GROCERY + types.API_DELETE_PRODUCT_GROCERY;

export const API_ADD_PRODUCT = BASE_URL_PRODUCT + types.API_ADD_PRODUCT;
export const API_ADD_PRODUCT_GROCERY =
	BASE_URL_PRODUCT_GROCERY + types.API_ADD_PRODUCT_GROCERY;
export const API_GET_PRODUCT_LIST =
	BASE_URL_PRODUCT + types.API_GET_PRODUCT_LIST;
export const API_GET_PRODUCT_LIST_GROCERY =
	BASE_URL_PRODUCT_GROCERY + types.API_GET_PRODUCT_LIST_GROCERY;
export const API_DELETE_PRODUCT = BASE_URL_PRODUCT + types.API_DELETE_PRODUCT;
//export const API_DELETE_PRODUCT_GROCERY = BASE_URL_PRODUCT + types.API_DELETE_PRODUCT_GROCERY;
export const API_EDIT_PRODUCT = BASE_URL_PRODUCT + types.API_EDIT_PRODUCT;
export const API_EDIT_PRODUCT_GROCERY =
	BASE_URL_PRODUCT_GROCERY + types.API_EDIT_PRODUCT_GROCERY;
export const API_PRODUCT_DETAILS = BASE_URL_PRODUCT + types.API_PRODUCT_DETAILS;
export const API_PRODUCT_DETAILS_GROCERY =
	BASE_URL_PRODUCT_GROCERY + types.API_PRODUCT_DETAILS_GROCERY;

export const API_DRIVER_LIST = BASE_URL_DRIVER + types.API_DRIVER_LIST;
export const API_DRIVER_LIST_GROCERY =
	BASE_URL_GROCERY_DRIVER + types.API_DRIVER_LIST;
export const API_LIST_REQ_DRIVER = BASE_URL_DRIVER + types.API_LIST_REQ_DRIVER;
export const API_LIST_REQ_DRIVER_GROCERY =
	BASE_URL_GROCERY_DRIVER + types.API_LIST_REQ_DRIVER_GROCERY;
export const API_CHANGE_REQ_DRIVER_STATUS =
	BASE_URL_DRIVER + types.API_CHANGE_REQ_DRIVER_STATUS;
export const API_CHANGE_REQ_DRIVER_STATUS_GROCERY =
	BASE_URL_GROCERY_DRIVER + types.API_CHANGE_REQ_DRIVER_STATUS_GROCERY;
export const API_ADD_DRIVER = BASE_URL_DRIVER + types.API_ADD_DRIVER;
export const API_ADD_DRIVER_GROCERY =
	BASE_URL_GROCERY_DRIVER + types.API_ADD_DRIVER_GROCERY;
export const API_DRIVER_DETAILS = BASE_URL_DRIVER + types.API_DRIVER_DETAILS;
export const API_DRIVER_DETAILS_GROCERY =
	BASE_URL_GROCERY_DRIVER + types.API_DRIVER_DETAILS_GROCERY;
export const API_EDIT_DRIVER = BASE_URL_DRIVER + types.API_EDIT_DRIVER;
export const API_EDIT_DRIVER_GROCERY =
	BASE_URL_GROCERY_DRIVER + types.API_EDIT_DRIVER_GROCERY;
export const API_DELETE_DRIVER = BASE_URL_DRIVER + types.API_DELETE_DRIVER;
export const API_DELETE_DRIVER_GROCERY =
	BASE_URL_GROCERY_DRIVER + types.API_DELETE_DRIVER_GROCERY;
export const API_DRIVER_CURRENT_LOC =
	BASE_URL_DRIVER + types.API_DRIVER_CURRENT_LOC;
export const API_DRIVER_CURRENT_LOC_GROCERY =
	BASE_URL_GROCERY_DRIVER + types.API_DRIVER_CURRENT_LOC_GROCERY;

//  Api floating cash for driver::::::

export const API_FLOATING_CASH_FOR_ALL_DRIVER =
	BASE_URL_DRIVER + types.API_FLOATING_CASH_FOR_ALL_DRIVER;
export const API_FLOATING_CASH_FOR_ALL_DRIVER_GROCERY =
	BASE_URL_GROCERY_DRIVER + types.API_FLOATING_CASH_FOR_ALL_DRIVER_GROCERY;

export const API_RECEIVE_FLOATING_CASH =
	BASE_URL_DRIVER + types.API_RECEIVE_FLOATING_CASH;
export const API_RECEIVE_FLOATING_CASH_GROCERY =
	BASE_URL_GROCERY_DRIVER + types.API_RECEIVE_FLOATING_CASH_GROCERY;

// user  api slugs
export const API_USER_LIST = BASE_URL + types.API_USER_LIST;
export const API_USER_LIST_GROCERY = BASE_URL + types.API_USER_LIST_GROCERY;
export const API_EDIT_USER = BASE_URL + types.API_EDIT_USER;
export const API_EDIT_USER_GROCERY = BASE_URL + types.API_EDIT_USER_GROCERY;
export const API_ADD_USER = BASE_URL + types.API_ADD_USER;
export const API_ADD_USER_GROCERY = BASE_URL + types.API_ADD_USER_GROCERY;

export const API_DELETE_USER = BASE_URL + types.API_DELETE_USER;
export const API_DELETE_USER_GROCERY = BASE_URL + types.API_DELETE_USER_GROCERY;
export const API_CHANGE_USER_STATUS = BASE_URL + types.API_CHANGE_USER_STATUS;
export const API_CHANGE_USER_STATUS_GROCERY =
	BASE_URL + types.API_CHANGE_USER_STATUS_GROCERY;

export const API_ADD_COUNTRY = BASE_URL + types.API_ADD_COUNTRY;
export const API_EDIT_COUNTRY = BASE_URL + types.API_EDIT_COUNTRY;
export const API_COUNTRY_LIST = BASE_URL + types.API_COUNTRY_LIST;
export const API_DELETE_COUNTRY = BASE_URL + types.API_DELETE_COUNTRY;

export const API_ADD_STATE = BASE_URL + types.API_ADD_STATE;
export const API_EDIT_STATE = BASE_URL + types.API_EDIT_STATE;
export const API_DELETE_STATE = BASE_URL + types.API_DELETE_STATE;
export const API_STATE_LIST = BASE_URL + types.API_STATE_LIST;

export const API_ADD_CITY = BASE_URL + types.API_ADD_CITY;
export const API_EDIT_CITY = BASE_URL + types.API_EDIT_CITY;
export const API_CITY_LIST = BASE_URL + types.API_CITY_LIST;
export const API_DELETE_CITY = BASE_URL + types.API_DELETE_CITY;

export const API_ADD_LOCALITY = BASE_URL + types.API_ADD_LOCALITY;
export const API_EDIT_LOCALITY = BASE_URL + types.API_EDIT_LOCALITY;
export const API_DELETE_LOCALITY = BASE_URL + types.API_DELETE_LOCALITY;
export const API_LOCALITY_LIST = BASE_URL + types.API_LOCALITY_LIST;
export const API_ORDER_LIST = BASE_URL_ORDER + types.API_ORDER_LIST;
export const API_ORDER_LIST_GROCERY =
	BASE_URL_ORDER_GROCERY + types.API_ORDER_LIST_GROCERY;
export const API_ORDER_LIST_FOR_ADMIN =
	BASE_URL_ORDER + types.API_ORDER_LIST_FOR_ADMIN;

export const API_ORDER_LIST_CANCEL_FOR_ADMIN =
	BASE_URL_ORDER + types.API_ORDER_LIST_CANCEL_FOR_ADMIN;

export const API_ORDER_LIST_FOR_ADMIN_GROCERY =
	BASE_URL_ORDER_GROCERY + types.API_ORDER_LIST_FOR_ADMIN_GROCERY;
export const API_CHANGE_ORDER_STATUS =
	BASE_URL_ORDER + types.API_CHANGE_ORDER_STATUS;
export const API_CHANGE_ORDER_STATUS_GROCERY =
	BASE_URL_ORDER_GROCERY + types.API_CHANGE_ORDER_STATUS_GROCERY;
export const API_LIST_DRIVER_EARNING =
	BASE_URL_ORDER + types.API_LIST_DRIVER_EARNING;
export const API_LIST_DRIVER_EARNING_GROCERY =
	BASE_URL_ORDER_GROCERY + types.API_LIST_DRIVER_EARNING_GROCERY;

export const API_LIST_SUPPORT_ISSUE = BASE_URL + types.API_LIST_SUPPORT_ISSUE;

export const API_LIST_ADMIN_EARNING =
	BASE_URL_ORDER + types.API_LIST_ADMIN_EARNING;
export const API_LIST_ADMIN_EARNING_GROCERY =
	BASE_URL_ORDER_GROCERY + types.API_LIST_ADMIN_EARNING_GROCERY;
export const API_LIST_RESTRO_EARNING =
	BASE_URL_ORDER + types.API_LIST_RESTRO_EARNING;
export const API_LIST_GROCERY_EARNING =
	BASE_URL_ORDER_GROCERY + types.API_LIST_GROCERY_EARNING;

export const API_CHANGE_STATUS_COUNTRY =
	BASE_URL + types.API_CHANGE_STATUS_COUNTRY;
export const API_CHANGE_STATUS_STATE = BASE_URL + types.API_CHANGE_STATUS_STATE;
export const API_CHANGE_STATUS_CITY = BASE_URL + types.API_CHANGE_STATUS_CITY;
export const API_CHANGE_STATUS_RESTRO =
	BASE_URL_RESTRO + types.API_CHANGE_STATUS_RESTRO;
export const API_CHANGE_STATUS_GROCERY =
	BASE_URL_GROCERY + types.API_CHANGE_STATUS_GROCERY;

export const API_CHANGE_STATUS_DRIVER =
	BASE_URL_DRIVER + types.API_CHANGE_STATUS_DRIVER;
export const API_CHANGE_STATUS_DRIVER_GROCERY =
	BASE_URL_GROCERY_DRIVER + types.API_CHANGE_STATUS_DRIVER_GROCERY;
export const API_CHANGE_STATUS_PRODUCT =
	BASE_URL_PRODUCT + types.API_CHANGE_STATUS_PRODUCT;
export const API_CHANGE_STATUS_PRODUCT_GROCERY =
	BASE_URL_PRODUCT_GROCERY + types.API_CHANGE_STATUS_PRODUCT_GROCERY;
export const API_CHANGE_STATUS_REQUESTED_RESTRO =
	BASE_URL_RESTRO + types.API_CHANGE_STATUS_REQUESTED_RESTRO;
export const API_CHANGE_STATUS_REQUESTED_GROCERY =
	BASE_URL_GROCERY + types.API_CHANGE_STATUS_REQUESTED_GROCERY;
export const API_LIST_REQUESTED_RESTRO =
	BASE_URL_RESTRO + types.API_LIST_REQUESTED_RESTRO;
export const API_LIST_REQUESTED_GROCERY =
	BASE_URL_GROCERY + types.API_LIST_REQUESTED_GROCERY;

export const API_ORDER_NEW = BASE_URL_ORDER + types.API_ORDER_NEW;
export const API_ORDER_NEW_GROCERY =
	BASE_URL_ORDER_GROCERY + types.API_ORDER_NEW_GROCERY;
export const API_ORDER_PREPARING = BASE_URL_ORDER + types.API_ORDER_PREPARING;
export const API_ORDER_PREPARING_GROCERY =
	BASE_URL_ORDER_GROCERY + types.API_ORDER_PREPARING_GROCERY;
export const API_ORDER_REDY = BASE_URL_ORDER + types.API_ORDER_REDY;
export const API_ORDER_REDY_GROCERY =
	BASE_URL_ORDER_GROCERY + types.API_ORDER_REDY_GROCERY;
export const API_ORDER_PAST_ORDER = BASE_URL_ORDER + types.API_ORDER_PAST_ORDER;
export const API_ORDER_PAST_ORDER_GROCERY =
	BASE_URL_ORDER_GROCERY + types.API_ORDER_PAST_ORDER_GROCERY;
export const API_ORDER_DETAILS = BASE_URL_ORDER + types.API_ORDER_DETAILS;
export const API_ORDER_DETAILS_GROCERY =
	BASE_URL_ORDER_GROCERY + types.API_ORDER_DETAILS_GROCERY;

export const API_DRIVER_DISTANCE_CHARGE =
	BASE_URL_DRIVER + types.API_DRIVER_DISTANCE_CHARGE;
export const API_DRIVER_DISTANCE_CHARGE_GROCERY =
	BASE_URL_GROCERY_DRIVER + types.API_DRIVER_DISTANCE_CHARGE_GROCERY;
export const API_EDIT_DRIVER_DISTANCE_CHARGE =
	BASE_URL_DRIVER + types.API_EDIT_DRIVER_DISTANCE_CHARGE;
export const API_EDIT_DRIVER_DISTANCE_CHARGE_GROCERY =
	BASE_URL_GROCERY_DRIVER + types.API_EDIT_DRIVER_DISTANCE_CHARGE_GROCERY;
export const API_DRIVER_DISTANCE_CHARGE_DETAILS =
	BASE_URL_DRIVER + types.API_DRIVER_DISTANCE_CHARGE_DETAILS;
export const API_DRIVER_DISTANCE_CHARGE_LIST_GROCERY =
	BASE_URL_GROCERY_DRIVER + types.API_DRIVER_DISTANCE_CHARGE_LIST_GROCERY;
export const API_DRIVER_DISTANCE_CHARGE_LIST =
	BASE_URL_DRIVER + types.API_DRIVER_DISTANCE_CHARGE_LIST;
export const API_DRIVER_DISTANCE_CHARGE_ITEM_DELETE =
	BASE_URL_DRIVER + types.API_DRIVER_DISTANCE_CHARGE_ITEM_DELETE;
export const API_DRIVER_DISTANCE_CHARGE_ITEM_DELETE_GROCERY =
	BASE_URL_GROCERY_DRIVER +
	types.API_DRIVER_DISTANCE_CHARGE_ITEM_DELETE_GROCERY;
export const API_DRIVER_DISTANCE_CHARGE_CHILD_DELETE =
	BASE_URL_DRIVER + types.API_DRIVER_DISTANCE_CHARGE_CHILD_DELETE;
export const API_DRIVER_DISTANCE_CHARGE_CHILD_DELETE_GROCERY =
	BASE_URL_GROCERY_DRIVER +
	types.API_DRIVER_DISTANCE_CHARGE_CHILD_DELETE_GROCERY;
export const API_DRIVER_DOC_STATUS_CHANGE =
	BASE_URL_DRIVER + types.API_DRIVER_DOC_STATUS_CHANGE;
export const API_DRIVER_DOC_STATUS_CHANGE_GROCERY =
	BASE_URL_GROCERY_DRIVER + types.API_DRIVER_DOC_STATUS_CHANGE_GROCERY;
export const API_NEED_TO_PAY_FOR_ALL_DRIVERS =
	BASE_URL_DRIVER + types.API_NEED_TO_PAY_FOR_ALL_DRIVERS;
export const API_NEED_TO_PAY_FOR_ALL_DRIVERS_GROCERY =
	BASE_URL_GROCERY_DRIVER + types.API_NEED_TO_PAY_FOR_ALL_DRIVERS_GROCERY;
export const API_PAID_DRIVER_PAYMENT =
	BASE_URL_DRIVER + types.API_PAID_DRIVER_PAYMENT;
export const API_PAID_DRIVER_PAYMENT_GROCERY =
	BASE_URL_GROCERY_DRIVER + types.API_PAID_DRIVER_PAYMENT_GROCERY;

export const API_PAID_RESTRO_PAYMENT =
	BASE_URL_RESTRO + types.API_PAID_RESTRO_PAYMENT;
export const API_PAID_GROCERY_PAYMENT =
	BASE_URL_GROCERY + types.API_PAID_GROCERY_PAYMENT;
export const API_NEED_TO_PAY_FOR_ALL_RESTRO =
	BASE_URL_RESTRO + types.API_NEED_TO_PAY_FOR_ALL_RESTRO;
export const API_NEED_TO_PAY_FOR_ALL_GROCERY =
	BASE_URL_GROCERY + types.API_NEED_TO_PAY_FOR_ALL_GROCERY;

export const API_GET_ISSUE_CREATED_DRIVER_LIST =
	BASE_URL + types.API_GET_ISSUE_CREATED_DRIVER_LIST;

export const API_LISTCOUPONCODE = BASE_URL + types.API_LISTCOUPONCODE;
export const API_ADDCOUPONCODE = BASE_URL + types.API_ADDCOUPONCODE;
export const API_DELETECOUPONCODE = BASE_URL + types.API_DELETECOUPONCODE;
export const API_CHANGECOUPONCODESTATUS =
	BASE_URL + types.API_CHANGECOUPONCODESTATUS;
export const API_EDITCOUPONCODE = BASE_URL + types.API_EDITCOUPONCODE;

export const API_LISTCOUPONCODE_GROCERY =
	BASE_URL + types.API_LISTCOUPONCODE_GROCERY;
export const API_ADDCOUPONCODE_GROCERY =
	BASE_URL + types.API_ADDCOUPONCODE_GROCERY;
export const API_DELETECOUPONCODE_GROCERY =
	BASE_URL + types.API_DELETECOUPONCODE_GROCERY;
export const API_CHANGECOUPONCODESTATUS_GROCERY =
	BASE_URL + types.API_CHANGECOUPONCODESTATUS_GROCERY;
export const API_EDITCOUPONCODE_GROCERY =
	BASE_URL + types.API_EDITCOUPONCODE_GROCERY;

export const API_RESTRO_DOC_STATUS_CHANGE =
	BASE_URL_RESTRO + types.API_RESTRO_DOC_STATUS_CHANGE;
export const API_GROCERY_DOC_STATUS_CHANGE =
	BASE_URL_GROCERY + types.API_GROCERY_DOC_STATUS_CHANGE;
export const API_RATING_REVIEW_LIST = BASE_URL + types.API_RATING_REVIEW_LIST;
export const API_RATING_REVIEW_LIST_GROCERY =
	BASE_URL + types.API_RATING_REVIEW_LIST_GROCERY;

// jyotish office api

export const API_ADD_OFFICE = BASE_URL_OFFICE + types.API_ADD_OFFICE;
export const API_ADD_OFFICE_GROCERY =
	BASE_URL_OFFICE_GROCERY + types.API_ADD_OFFICE_GROCERY;
export const API_OFFICE_LIST = BASE_URL_OFFICE + types.API_OFFICE_LIST;
export const API_OFFICE_LIST_GROCERY =
	BASE_URL_OFFICE_GROCERY + types.API_OFFICE_LIST_GROCERY;
export const API_OFFICE_DETAIL_GROCERY =
	BASE_URL_OFFICE_GROCERY + types.API_OFFICE_DETAIL_GROCERY;
export const API_OFFICE_DETAIL = BASE_URL_OFFICE + types.API_OFFICE_DETAIL;
//export const SCREEN_ADD_OFFICE = BASE_URL_OFFICE + types.SCREEN_ADD_OFFICE;
export const API_DELETE_OFFICE = BASE_URL_OFFICE + types.API_DELETE_OFFICE;
export const API_DELETE_OFFICE_GROCERY =
	BASE_URL_OFFICE_GROCERY + types.API_DELETE_OFFICE_GROCERY;
export const API_OFFICE_STATUS_CHANGE =
	BASE_URL_OFFICE + types.API_OFFICE_STATUS_CHANGE;
export const API_OFFICE_STATUS_CHANGE_GROCERY =
	BASE_URL_OFFICE_GROCERY + types.API_OFFICE_STATUS_CHANGE_GROCERY;
export const SCREEN_EDIT_OFFICE =
	BASE_URL_OFFICE + types.API_RATING_REVIEW_LIST;
export const SCREEN_EDIT_OFFICE_GROCERY =
	BASE_URL_OFFICE_GROCERY + types.API_RATING_REVIEW_LIST_GROCERY;

export const API_USER_TYPE_FOR_REPORT =
	BASE_URL + types.API_USER_TYPE_FOR_REPORT;
export const API_GENERATE_REPORT = BASE_URL + types.API_GENERATE_REPORT;
export const API_REPORT_HISTORY_RETSTRO =
	BASE_URL + types.API_REPORT_HISTORY_RETSTRO;

export const API_ADD_DISCOUNT = BASE_URL + types.API_ADD_DISCOUNT;
export const API_DISCOUNT_LIST = BASE_URL + types.API_DISCOUNT_LIST;
export const API_EDIT_DISCOUNT = BASE_URL + types.API_EDIT_DISCOUNT;
export const API_DISCOUNT_DETAILS = BASE_URL + types.API_DISCOUNT_DETAILS;
export const API_CHANGE_DISCOUNT_STATUS =
	BASE_URL + types.API_CHANGE_DISCOUNT_STATUS;

export const API_ADD_DISCOUNT_GROCERY =
	BASE_URL + types.API_ADD_DISCOUNT_GROCERY;
export const API_DISCOUNT_LIST_GROCERY =
	BASE_URL + types.API_DISCOUNT_LIST_GROCERY;
export const API_EDIT_DISCOUNT_GROCERY =
	BASE_URL + types.API_EDIT_DISCOUNT_GROCERY;
export const API_DISCOUNT_DETAILS_GROCERY =
	BASE_URL + types.API_DISCOUNT_DETAILS_GROCERY;
export const API_CHANGE_DISCOUNT_STATUS_GROCERY =
	BASE_URL + types.API_CHANGE_DISCOUNT_STATUS_GROCERY;

export const API_RESTRO_ONLINE_STATUS_CHANGE =
	BASE_URL_RESTRO + types.API_RESTRO_ONLINE_STATUS_CHANGE;
export const API_GROCERY_ONLINE_STATUS_CHANGE =
	BASE_URL_GROCERY + types.API_GROCERY_ONLINE_STATUS_CHANGE;
export const API_SELECTED_CATEGORY = BASE_URL + types.API_SELECTED_CATEGORY;
export const API_SELECTED_CATEGORY_GROCERY =
	BASE_URL + types.API_SELECTED_CATEGORY_GROCERY;
export const API_ADD_ADMIN_COMMISSION =
	BASE_URL + types.API_ADD_ADMIN_COMMISSION;
export const API_ADD_ADMIN_COMMISSION_GROCERY =
	BASE_URL + types.API_ADD_ADMIN_COMMISSION_GROCERY;
export const API_EDIT_ADMIN_COMMISSION =
	BASE_URL + types.API_EDIT_ADMIN_COMMISSION;
export const API_EDIT_ADMIN_COMMISSION_GROCERY =
	BASE_URL + types.API_EDIT_ADMIN_COMMISSION_GROCERY;
export const API_ADMIN_COMMISSION_CHARGE_LIST =
	BASE_URL + types.API_ADMIN_COMMISSION_CHARGE_LIST;
export const API_ADMIN_COMMISSION_CHARGE_LIST_GROCERY =
	BASE_URL + types.API_ADMIN_COMMISSION_CHARGE_LIST_GROCERY;
export const API_DELETE_ADMIN_COMMISSION_CHARGE_ITEM =
	BASE_URL + types.API_DELETE_ADMIN_COMMISSION_CHARGE_ITEM;
export const API_DELETE_ADMIN_COMMISSION_CHARGE_ITEM_GROCERY =
	BASE_URL + types.API_DELETE_ADMIN_COMMISSION_CHARGE_ITEM_GROCERY;
export const API_DRIVER_EARNING_PER_WEEK =
	BASE_URL_ORDER + types.API_DRIVER_EARNING_PER_WEEK;
export const API_DRIVER_EARNING_PER_WEEK_GROCERY =
	BASE_URL_ORDER_GROCERY + types.API_DRIVER_EARNING_PER_WEEK_GROCERY;
export const API_RESTRO_EARNING_PER_WEEK =
	BASE_URL_ORDER + types.API_RESTRO_EARNING_PER_WEEK;
export const API_GROCERY_EARNING_PER_WEEK =
	BASE_URL_ORDER_GROCERY + types.API_GROCERY_EARNING_PER_WEEK;
export const API_ADMIN_EARNING_PER_WEEK =
	BASE_URL_ORDER + types.API_ADMIN_EARNING_PER_WEEK;
export const API_ADMIN_EARNING_PER_WEEK_GROCERY =
	BASE_URL_ORDER_GROCERY + types.API_ADMIN_EARNING_PER_WEEK_GROCERY;
export const API_ADD_ORDER_DILEVERY_CHARGE =
	BASE_URL_ORDER + types.API_ADD_ORDER_DILEVERY_CHARGE;
export const API_ADD_ORDER_DILEVERY_CHARGE_GROCERY =
	BASE_URL_ORDER_GROCERY + types.API_ADD_ORDER_DILEVERY_CHARGE_GROCERY;
export const API_ORDER_COMPLETED_GROCERY =
	BASE_URL_ORDER_GROCERY + types.API_ORDER_COMPLETED_GROCERY;
export const API_ORDER_COMPLETED = BASE_URL_ORDER + types.API_ORDER_COMPLETED;

export const API_ORDER_DILEVERY_CHARGE_LIST =
	BASE_URL_ORDER + types.API_ORDER_DILEVERY_CHARGE_LIST;
export const API_ORDER_DILEVERY_CHARGE_LIST_GROCERY =
	BASE_URL_ORDER_GROCERY + types.API_ORDER_DILEVERY_CHARGE_LIST_GROCERY;
export const API_EDIT_ORDER_DILEVERY_CHARGE =
	BASE_URL_ORDER + types.API_EDIT_ORDER_DILEVERY_CHARGE;
export const API_EDIT_ORDER_DILEVERY_CHARGE_GROCERY =
	BASE_URL_ORDER_GROCERY + types.API_EDIT_ORDER_DILEVERY_CHARGE_GROCERY;
export const API_DELETE_ORDER_DILEVERY_CHARGE =
	BASE_URL_ORDER + types.API_DELETE_ORDER_DILEVERY_CHARGE;
export const API_DELETE_ORDER_DILEVERY_CHARGE_GROCERY =
	BASE_URL_ORDER_GROCERY + types.API_DELETE_ORDER_DILEVERY_CHARGE_GROCERY;
export const REPORT = BASE_URL + types.API_REPORT;
export const API_ORDER_CANCEL_MANEGMENT =
	BASE_URL + types.API_ORDER_CANCEL_MANEGMENT;
